graph TD
    %% Call Graph - Who calls whom
    %% Arrows point from caller to callee

    TestSalesInvoice_test_additional_discount_for_sales_invoice_with_discount_accounting_enabled[TestSalesInvoice.test_additional_discount_for_sales_invoice_with_discount_accounting_enabled] -->|15x| nowdate[nowdate]
    make_inter_company_transaction_update_details[make_inter_company_transaction.update_details] -->|13x| details_get[details.get]
    TestSalesInvoice_test_sales_invoice_calculation_export_currency_with_tax_inclusive_price[TestSalesInvoice.test_sales_invoice_calculation_export_currency_with_tax_inclusive_price] -->|12x| self_assertEqual[self.assertEqual]
    TestSalesInvoice_test_partial_allocation_on_advance_as_liability[TestSalesInvoice.test_partial_allocation_on_advance_as_liability] -->|12x| nowdate[nowdate]
    TestSalesInvoice_test_rounding_adjustment_3[TestSalesInvoice.test_rounding_adjustment_3] -->|11x| self_assertEqual[self.assertEqual]
    TestSalesInvoice_test_tax_calculation_with_item_tax_template[TestSalesInvoice.test_tax_calculation_with_item_tax_template] -->|10x| self_assertEqual[self.assertEqual]
    TestSalesInvoice_test_discount_on_net_total[TestSalesInvoice.test_discount_on_net_total] -->|10x| self_assertEqual[self.assertEqual]
    SalesInvoice_validate_debit_to_acc[SalesInvoice.validate_debit_to_acc] -->|10x| _[_]
    TestSalesInvoice_test_sales_invoice_calculation_export_currency[TestSalesInvoice.test_sales_invoice_calculation_export_currency] -->|9x| self_assertEqual[self.assertEqual]
    TestSalesInvoice_test_ledger_entries_of_return_pos_invoice[TestSalesInvoice.test_ledger_entries_of_return_pos_invoice] -->|9x| self_assertEqual[self.assertEqual]
    SalesInvoice_set_pos_fields[SalesInvoice.set_pos_fields] -->|9x| pos_get[pos.get]
    SalesInvoice_make_write_off_gl_entry[SalesInvoice.make_write_off_gl_entry] -->|9x| flt[flt]
    SalesInvoice_make_write_off_gl_entry[SalesInvoice.make_write_off_gl_entry] -->|9x| self_precision[self.precision]
    TestSalesInvoice_test_sales_invoice_calculation_export_currency[TestSalesInvoice.test_sales_invoice_calculation_export_currency] -->|8x| si_get[si.get]
    TestSalesInvoice_test_sales_invoice_with_discount_and_inclusive_tax[TestSalesInvoice.test_sales_invoice_with_discount_and_inclusive_tax] -->|8x| self_assertEqual[self.assertEqual]
    TestSalesInvoice_test_sales_invoice_discount_amount[TestSalesInvoice.test_sales_invoice_discount_amount] -->|8x| self_assertEqual[self.assertEqual]
    TestSalesInvoice_test_sales_invoice_calculation_base_currency_with_tax_inclusive_price[TestSalesInvoice.test_sales_invoice_calculation_base_currency_with_tax_inclusive_price] -->|8x| self_assertEqual[self.assertEqual]
    TestSalesInvoice_test_sales_invoice_calculation_export_currency_with_tax_inclusive_price[TestSalesInvoice.test_sales_invoice_calculation_export_currency_with_tax_inclusive_price] -->|8x| si_get[si.get]
    SalesInvoice_set_missing_values[SalesInvoice.set_missing_values] -->|8x| pos_get[pos.get]
    TestSalesInvoice_test_sales_invoice_calculation_base_currency[TestSalesInvoice.test_sales_invoice_calculation_base_currency] -->|7x| self_assertEqual[self.assertEqual]
    TestSalesInvoice_test_tax_calculation_with_item_tax_template[TestSalesInvoice.test_tax_calculation_with_item_tax_template] -->|7x| si_get[si.get]
    TestSalesInvoice_test_return_sales_invoice[TestSalesInvoice.test_return_sales_invoice] -->|7x| self_assertEqual[self.assertEqual]
    TestSalesInvoice_test_rounding_adjustment[TestSalesInvoice.test_rounding_adjustment] -->|7x| self_assertEqual[self.assertEqual]
    TestSalesInvoice_test_rounding_adjustment_2[TestSalesInvoice.test_rounding_adjustment_2] -->|7x| self_assertEqual[self.assertEqual]
    create_sales_invoice[create_sales_invoice] -->|7x| args_get[args.get]
    make_inter_company_transaction_update_details[make_inter_company_transaction.update_details] -->|7x| _validate_address_link[_validate_address_link]
    make_inter_company_transaction_update_details[make_inter_company_transaction.update_details] -->|7x| update_address[update_address]
    TestSalesInvoice_test_bin_details_of_packed_item[TestSalesInvoice.test_bin_details_of_packed_item] -->|6x| flt[flt]
    TestSalesInvoice_test_serialized[TestSalesInvoice.test_serialized] -->|6x| si_get[si.get]
    TestSalesInvoice_test_return_sales_invoice[TestSalesInvoice.test_return_sales_invoice] -->|6x| frappe_db_get_value[frappe.db.get_value]
    TestSalesInvoice_test_internal_transfer_gl_entry[TestSalesInvoice.test_internal_transfer_gl_entry] -->|6x| nowdate[nowdate]
    SalesInvoice_validate_fixed_asset[SalesInvoice.validate_fixed_asset] -->|6x| _[_]
    SalesInvoice_validate_pos_opening_entry[SalesInvoice.validate_pos_opening_entry] -->|6x| _[_]
    SalesInvoice_get_gl_entries_for_fixed_asset[SalesInvoice.get_gl_entries_for_fixed_asset] -->|6x| self_get[self.get]
    TestSalesInvoice_test_tax_calculation_with_multiple_items_and_discount[TestSalesInvoice.test_tax_calculation_with_multiple_items_and_discount] -->|5x| self_assertEqual[self.assertEqual]
    TestSalesInvoice_test_inclusive_rate_validations[TestSalesInvoice.test_inclusive_rate_validations] -->|5x| si_get[si.get]
    TestSalesInvoice_test_invalid_currency[TestSalesInvoice.test_invalid_currency] -->|5x| create_sales_invoice[create_sales_invoice]
    TestSalesInvoice_test_outstanding_amount_after_advance_payment_entry_cancellation[TestSalesInvoice.test_outstanding_amount_after_advance_payment_entry_cancellation] -->|5x| self_assertEqual[self.assertEqual]
    TestSalesInvoice_test_asset_depreciation_on_sale_without_pro_rata[TestSalesInvoice.test_asset_depreciation_on_sale_without_pro_rata] -->|5x| getdate[getdate]
    TestSalesInvoice_test_advance_entries_as_liability[TestSalesInvoice.test_advance_entries_as_liability] -->|5x| nowdate[nowdate]
    TestSalesInvoice_test_sales_invoice_without_customer_group_and_territory[TestSalesInvoice.test_sales_invoice_without_customer_group_and_territory] -->|5x| self_assertEqual[self.assertEqual]
    TestSalesInvoice_test_non_batchwise_valuation_for_moving_average[TestSalesInvoice.test_non_batchwise_valuation_for_moving_average] -->|5x| self_assertEqual[self.assertEqual]
    SalesInvoice_set_indicator[SalesInvoice.set_indicator] -->|5x| _[_]
    SalesInvoice_validate_fixed_asset[SalesInvoice.validate_fixed_asset] -->|5x| frappe_throw[frappe.throw]
    SalesInvoice_make_gl_entries[SalesInvoice.make_gl_entries] -->|5x| cint[cint]
    SalesInvoice_make_tax_gl_entries[SalesInvoice.make_tax_gl_entries] -->|5x| flt[flt]
    SalesInvoice_make_item_gl_entries[SalesInvoice.make_item_gl_entries] -->|5x| flt[flt]
    SalesInvoice_make_item_gl_entries[SalesInvoice.make_item_gl_entries] -->|5x| item_precision[item.precision]
    validate_inter_company_party[validate_inter_company_party] -->|5x| _[_]
    make_delivery_note_update_item[make_delivery_note.update_item] -->|5x| flt[flt]